# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellentry',
            name='emailSeller',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sellentry',
            name='sellerNumber',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sellentry',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sellentry',
            name='itemName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sellentry',
            name='latOfSeller',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sellentry',
            name='locationOfSeller',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sellentry',
            name='longOfSeller',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sellentry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sellentry',
            name='sellerName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
