# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20171112_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellentry',
            name='datePosted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
