# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('sellerName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('locationOfSeller', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latOfSeller', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longOfSeller', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
